SecuredVotingSystem/SecuredVotingSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dadmin/', admin.site.urls),
    path('', include('votingapp.urls')),
]

SecuredVotingSystem/votingapp/urls.py
from django.urls import path
from .views import Home, OTP, vote, add_nominee
app_name = 'votingapp'

urlpatterns = [
    path('', Home, name='Home'),
    path('otp', OTP, name='otp'),
    path('vote', vote, name='vote'),
    path('add-nominee/', add_nominee, name='add_nominee'),
]

SecuredVotingSystem/votingapp/models.py
from django.db import models

# Create your models here.
class VoteNominee(models.Model):
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='static/nomineephotos')
    position = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

SecuredVotingSystem/votingapp/views.py
# imports
from django.shortcuts import render, HttpResponse, redirect
import json
from .models import VoteNominee

# Create your views here.
# view to handle ajax request
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def Home(request):
    return render(request, 'index.html')


def OTP(request):
    if request.method == 'GET':
        return render(request, 'otp.html')

    if is_ajax(request) and request.method == 'POST':
        print(request.POST)
        successful_json = {'value': True}
        unsuccessful_json = {'value': False}
        otp = request.POST['otp']
        # todo: work on retrieving and validating otp here
        if int(otp) == 1415:
            return HttpResponse(json.dumps(successful_json))
        else:
            return HttpResponse(json.dumps(unsuccessful_json))


def add_nominee(request):
    if request.method == 'POST':
        name = request.POST['name']
        photo = request.FILES['photo']
        position = request.POST['position']

        nominee = VoteNominee(name=name, photo=photo, position=position)
        nominee.save()

        return redirect('votingapp:add_nominee')  # Redirect to a success page or the desired URL

    return render(request, 'addnominee.html')
def vote(request):
    if request.method == 'GET':
        nominees = VoteNominee.objects.all()
        president = list()
        vice = list()
        for nom in nominees:
            if nom.position == 'president':
                president.append(nom)
            else:
                vice.append(nom)
        context = {'presidents':president, 'vices':vice}
        return render(request, 'vote.html', context)
    if is_ajax(request) and request.method == 'POST':

        #add votes to user
        try:
            print(request.POST)
            votes =[]
            for itm in request.POST:
                if type(itm) == str:
                    votes.append(itm.split(',')[0])
                    votes.append(itm.split(',')[1])

            successful_json = {'value':True}
            print(votes)
            #strip spaces
            for v in votes:
                votes[votes.index(v)] = v.replace(" ", "")
            for v in votes:
                print(v)
                nomObj = VoteNominee.objects.get(name=str(v))
                nomObj.votes = nomObj.votes +1
                nomObj.save()
            return HttpResponse(json.dumps(successful_json))
        except Exception as e:
            unsuccessful_json = {'value': False}
            print(e)
            return HttpResponse(json.dumps(unsuccessful_json))

SecuredVotingSystem/votingapp/templates/addnominee.html
{% extends 'baselayout.html' %}
{% load static %}
{% block links %}
<link href="{% static 'css/addnominee.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/fundamental.js' %}"></script>
{% endblock links %}
{% block title %}Add Nominee{% endblock title %}
{% block body %}
 % block content %}
  <h2>Add New Nominee</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
      <label for="name">Name:</label>
      <input type="text" name="name" id="name" required>
    </div>

    <div class="form-group">
      <label for="photo">Photo:</label>
      <input type="file" name="photo" id="photo" required>
    </div>

    <div class="form-group">
      <label for="position">Position:</label>
      <select name="position" id="position" required>
        <option value="">Select Position</option>
        <option value="president">President</option>
        <option value="vice_president">Vice President</option>
      </select>
    </div>

    <button type="submit">Add Nominee</button>
  </form>
{% endblock %}

SecuredVotingSystem/votingapp/templates/baselayout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--links-->

    <script src="{% static 'js/jquery.min.js' %}"></script>

    <script src="{% static 'js/fundamental.js' %}"></script>
    {% block links %}<link href="{% static 'css/baselayout.css' %}" rel="stylesheet" type="text/css">{% endblock links %}
    {% block plinks %}{% endblock plinks %}
    <title>{% block title %}E-voting App{% endblock title %}</title>
</head>
<body>
{% block body %}
{% endblock body %}
</body>
</html>

SecuredVotingSystem/votingapp/templates/index.html
{% extends 'baselayout.html' %}
{% load static %}

{% block body %}
<div class="banner">
    <h1>E-voting Application</h1>
  </div>

  <div class="content">
      <div class="container">
          <div class="box">
    <div class="terms">
      <h2>Terms of Agreement</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet lectus ut lectus rhoncus scelerisque. Duis sodales lacus nec libero ultrices dictum.</p>
        <a href="{% url 'votingapp:otp' %}"><button class="start-vote-button">Start Vote</button></a>
    </div>
  </div>
      </div>
  </div>
{% endblock body %}

SecuredVotingSystem/votingapp/templates/otp.html
{% extends 'baselayout.html' %}
{% load static %}
{% block links %}
<link href="{% static 'css/otp.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/otp.min.js' %}"></script>
<script src="{% static 'js/fundamental.js' %}"></script>
{% endblock links %}
{% block title %}
OTP VERIFICATION
{% endblock title %}
{% block body %}
<div class="container">
    <h1 class="banner">OTP</h1>
    {% csrf_token %}
    <input id="otp" type="text" class="otp-input" placeholder="Enter OTP">
  </div>
{% endblock body %}

SecuredVotingSystem/votingapp/templates/vote.html
{% extends 'baselayout.html' %}

{% load static %}
{% block links %}
<link href="{% static 'css/vote.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/vote.min.js' %}"></script>
<script src="{% static 'js/fundamental.js' %}"></script>
{% endblock links %}
{% block title %}Vote{% endblock title %}

{% block body %}
<header><div class="banner">
    <h1>E-voting In Progress</h1>
</div></header>
<div>
  <div class="pos-banner">
    <h1>President</h1>
</div>
<div class="main-content1">
  {% if presidents %}
  {% for pres in presidents %}
<div class="vote-option voting-div">
    <img class="voting-image" src="{{pres.photo}}" alt="Image 1">
  <h3 class="name">{{pres.name}}</h3>
    <button   class="voting-button">Vote</button>
  </div>
  {% endfor %}
  {% else %}
  <div>
  <div class="pos-banner">
    <h1>No president in database</h1>
</div>
  {% endif %}

</div>
</div>
<div>
  <div class="pos-banner">
    <h1>Vice President</h1>
</div>
<div class="main-content2">
  {% if vices %}
  {% for vice in vices %}
<div class=" voting-div v2">
    <img class="voting-image" src="{{vice.photo}}" alt="Image ">
  <h3 class="name">{{vice.name}}</h3>
    <button   class=" vb2">Vote</button>
  </div>
  {% endfor %}
  {% else %}
  <div>
  <div class="pos-banner">
    <h1>No president in database</h1>
</div>
  {% endif %}
</div>

</div>
</div>
  <form id="vote-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Form fields here -->

    <button id="submit-button" class="submit-button">Submit</button>
  </form>
</div>
{% endblock body %}